// Clean-room reconstruction — per-character audio profiles (Systems M08), generated by tools/systems/
// gen_character_audio.py from AssetTools mp_content/roster_package.json + mp_weapons.json and authored.db (read-only)
// into CharacterAudio.inc. Nothing here is specific to one character: Optimus is just the default profile ("Truck").
//   voice    the robot SoundEventSet (CHR_*: FS_DEFAULT_* footsteps / jump / land, BF_* body, impacts, warcry,
//            death react) [CONF data]
//   vehicle  the vehicle SoundEventSet (Auto_Engine_Gear_*, Auto_Boost_*, Auto_Jump_*, Auto_Land_*, Auto_Ram_*, Auto_Tire_*
//            ...) [CONF data]
//   clips    the sound-bearing notifies of every clip in the robot anim sets (later sets override earlier ones for a
//            clip name [HIGH: UE3 FindAnimSequence]): AnimNotify_Footstep (Type -> HmFootstepComponent slot ->
//            FS_DEFAULT_* event, resolved through `voice`), HmAnimNotify_SoundEvent (event), HmAnimNotify_Sound (cue)
//            [CONF data]. The transform sounds are the notifies of Transform_ToVehicle_ROBO / Transform_ToRobot_ROBO.
//   death    the vehicle death sound; weapons: the iconic loadout, each weapon class's WeaponSounds events and
//            PickupSound [CONF data].
// Verified: the default profile reproduces the previous hand-made Optimus tables exactly (26 / 26 locomotion notifies,
// the landing / take-off / idle notifies, all 14 vehicle sounds, the transform cues).
#pragma once
#include <map>
#include <string>
#include <vector>

namespace game {

class SoundCues;

struct CharacterAudioProfile {
    struct Notify { float t; std::string event, cue; float minWeight; };   // event (resolved via voice) or cue
    struct Clip { float length; std::vector<Notify> notifies; };
    std::string key, name, faction, voiceSet, vehicleSet, vehicleDeath;
    std::map<std::string, std::string> voice, vehicle;
    std::map<std::string, Clip> clips;
    std::vector<std::string> weapons;

    // The cue a notify plays ("" = the set has no sound for its event).
    const std::string& notifyCue(const Notify& n) const;
    const std::string& voiceCue(const std::string& event) const;
    const std::string& vehicleCue(const std::string& event) const;
    const Clip* clip(const std::string& name) const;
};

// The hit effect a weapon's damage type selects in the victim's TnHitEffectPlayerBlueprint (SharedHitEffectPlayer),
// resolved by the generator with FindEffect's rule (exact DamageType, then the first ClassIsChildOf) [CONF script].
// hitEvent / blockEvent are sound EVENTS looked up in the VICTIM's SoundEventSet (CharacterAudioProfile::voice).
struct WeaponHitEffect {
    std::string damageType, hitEvent, blockEvent;
    int index = -1;              // entry index: the retrigger timer is per victim per entry
    float retrigger = 0.0f;      // RetriggerTime
    bool causesBlood = false;    // TnPawn.ShouldPlayHitEffect needs DamageType.bCausesBlood
};

class CharacterAudio {
public:
    static const CharacterAudioProfile* find(const std::string& keyOrName);   // roster chassis key or display name
    static const CharacterAudioProfile& defaultProfile();                    // "Truck" (Optimus Prime)
    static int profileCount();
    static std::vector<std::string> keys();
    // Load the cues the profile references that the cue table does not have yet (level-owned: released with the
    // level's cues). Returns the number added.
    static int loadCues(SoundCues& cues, const CharacterAudioProfile& p);
    // A weapon class's event cue (e.g. "TransContent.TnWeaponIonBlaster", "WP_Fire"); "" if none.
    static const std::string& weaponCue(const std::string& weaponClass, const std::string& event);
    static const std::string& weaponPickupSound(const std::string& weaponClass);
    static int loadWeaponCues(SoundCues& cues, const std::string& weaponClass);
    // The weapon's hit effect (nullptr: no entry matches its damage type -> no hit sound, as in the original).
    static const WeaponHitEffect* weaponHitEffect(const std::string& weaponClass);
    // Load the victim's hit / block cues for that weapon (level-owned). Returns the number added.
    static int loadHitCues(SoundCues& cues, const CharacterAudioProfile& victim, const std::string& weaponClass);
};

} // namespace game
