// Clean-room reconstruction — per-character audio profiles (Systems M08), generated by tools/systems/
// gen_character_audio.py from AssetTools mp_content/roster_package.json + mp_weapons.json and authored.db (read-only)
// into CharacterAudio.inc. Nothing here is specific to one character: Optimus is just the default profile ("Truck").
//   voice    the robot SoundEventSet (CHR_*: FS_DEFAULT_* footsteps / jump / land, BF_* body, impacts, warcry,
//            death react) [CONF data]
//   vehicle  the vehicle SoundEventSet (Auto_Engine_Gear_*, Auto_Boost_*, Auto_Jump_*, Auto_Land_*, Auto_Ram_*, Auto_Tire_*
//            ...) [CONF data]
//   clips    the sound-bearing notifies of every clip in the robot anim sets (later sets override earlier ones for a
//            clip name [HIGH: UE3 FindAnimSequence]): AnimNotify_Footstep (Type -> HmFootstepComponent slot ->
//            FS_DEFAULT_* event, resolved through `voice`), HmAnimNotify_SoundEvent (event), HmAnimNotify_Sound (cue)
//            [CONF data]. The transform sounds are the notifies of Transform_ToVehicle_ROBO / Transform_ToRobot_ROBO.
//   death    the vehicle death sound; weapons: the iconic loadout, each weapon class's WeaponSounds events and
//            PickupSound [CONF data].
// Verified: the default profile reproduces the previous hand-made Optimus tables exactly (26 / 26 locomotion notifies,
// the landing / take-off / idle notifies, all 14 vehicle sounds, the transform cues).
#pragma once
#include <cmath>
#include <map>
#include <string>
#include <vector>

namespace game {

class SoundCues;

// The vehicle form's HmPlayerVehicleAudioComponent [CONF data]: the object merged over its archetype chain and the
// HmVehicleAudioComponent / HmPlayerVehicleAudioComponent class defaults. Sounds are EVENT names, resolved through the
// chassis's vehicle SoundEventSet ("" = slot unset -> nothing plays).
struct VehicleAudioComponentData {
    struct Gear { float maxSpeed = 0.0f; std::vector<std::string> onLoops, onOneshots, offLoops, offOneshots; };
    struct Land { float t = 0.0f; std::string event; };
    bool valid = false;
    std::vector<Gear> drive;                   // DriveSounds (ComputeGear: first with speed <= MaxSpeed, else the last)
    Gear reverse;                              // ReverseSound
    std::vector<std::string> boostLoops, boostOneshots, jumpLoops, jumpOneshots;
    bool useJumpRev = false;                   // JumpRevSounds.UseJumpRev
    std::vector<Land> hoverLand, boostLand;    // TimeInAirThreshold ascending
    std::string boost, boostWheels, boostStop, ascend, ram, booster, nitro, squeal;
    std::string speed, ascendStop, descend, descendStop, roll, oneEighty, enter, exit, tread;
    float boostFadeIn = 0.1f, boostFadeOut = 0.1f, boostWheelsDelay = 0.25f, squealMinMph = 3.0f, squealFade = 0.1f;
    float engineFadeIn = 0.1f, engineFadeOut = 0.1f, jumpRevTime = 0.25f, oneshotSpazTime = 1.0f, treadFade = 0.1f;
    int speedHistory = 15;
};

// The vehicle form's particle effects [CONF data: VEHDEF HoverFX / BoostFx / JumpFX / RamFX; sockets on the vehicle
// mesh; TnAnimNotify_ToggleVehicleFx in the transform clips].
struct VehicleFxData {
    struct Entry { std::string templ, socket; };
    struct Socket { std::string bone; float rel[16]; float scale[3]; };   // rel: glTF, columns X = UE +X, Y = UE +Z
    std::vector<Entry> hover, boost, jump, ram;
    std::map<std::string, Socket> sockets;
    float enableFraction = 0.9f;   // Transform_ToVehicle_VEH ToggleVehicleFx (enable) time / clip length
    bool valid = false;
};

struct CharacterAudioProfile {
    struct Notify { float t; std::string event, cue; float minWeight; };   // event (resolved via voice) or cue
    struct Clip { float length; std::vector<Notify> notifies; };
    std::string key, name, faction, voiceSet, vehicleSet, vehicleDeath;
    std::map<std::string, std::string> voice, vehicle;
    std::map<std::string, Clip> clips;
    std::vector<std::string> weapons;
    VehicleAudioComponentData vehicleComponent;
    std::string vehicleForm;        // roster vehicle_form: "car" / "truck" / "tank" / "jet" (which form class)
    VehicleFxData vehicleFx;

    // The cue a notify plays ("" = the set has no sound for its event).
    const std::string& notifyCue(const Notify& n) const;
    const std::string& voiceCue(const std::string& event) const;
    const std::string& vehicleCue(const std::string& event) const;
    const Clip* clip(const std::string& name) const;
};

// The hit effect a weapon's damage type selects in the victim's TnHitEffectPlayerBlueprint (SharedHitEffectPlayer),
// resolved by the generator with FindEffect's rule (exact DamageType, then the first ClassIsChildOf) [CONF script].
// hitEvent / blockEvent are sound EVENTS looked up in the VICTIM's SoundEventSet (CharacterAudioProfile::voice).
struct WeaponHitEffect {
    std::string damageType, hitEvent, blockEvent;
    int index = -1;              // entry index: the retrigger timer is per victim per entry
    float retrigger = 0.0f;      // RetriggerTime
    bool causesBlood = false;    // TnPawn.ShouldPlayHitEffect needs DamageType.bCausesBlood
};

// A weapon mesh's animation sounds (HmAnimNotify_Sound on its own AnimSet) [CONF data]: the WeaponEventAnims
// sequences and the IdleAnimation sequence (<Seq>Group -> <Seq> [HIGH name rule]).
struct WeaponAnimSounds {
    struct Clip { std::string name; float length = 0.0f; std::vector<std::pair<float, std::string>> sounds; };
    Clip idle, fire, reload, equip, putDown;
};

// The weapon mesh's animation timeline, for its sounds only (the visual WeaponMesh is the Ion Blaster's; this follows
// the HELD weapon class). Same rules as WeaponMesh: an event anim replaces the current one, plays once and returns
// to the looping idle; a notify fires when its time is crossed (a notify at 0 on the first step; loops wrap).
class WeaponSoundTimeline {
public:
    enum class Event { Idle, Fire, Reload, Equip, PutDown };
    void set(const WeaponAnimSounds* s) { s_ = s; play(Event::Idle); }
    const WeaponAnimSounds* sounds() const { return s_; }
    void play(Event e) {
        cur_ = nullptr;
        if (!s_) return;
        const WeaponAnimSounds::Clip* c = e == Event::Fire ? &s_->fire : e == Event::Reload ? &s_->reload
                                        : e == Event::Equip ? &s_->equip : e == Event::PutDown ? &s_->putDown : &s_->idle;
        if (c->length <= 0.0f) c = &s_->idle;
        cur_ = c->length > 0.0f ? c : nullptr;
        t_ = 0.0f;
        loop_ = (c == &s_->idle);
    }
    const char* clip() const { return cur_ ? cur_->name.c_str() : "-"; }
    void tick(float dt, std::vector<const std::string*>& out) {
        if (!cur_) return;
        const float len = cur_->length;
        if (dt > 0.0f) {
            const float a = loop_ ? std::fmod(t_, len) : t_, b = a + dt;
            for (const auto& n : cur_->sounds)
                if ((n.first >= a && n.first < b) || (loop_ && b > len && n.first < b - len)) out.push_back(&n.second);
        }
        t_ += dt;
        if (!loop_ && t_ >= len) play(Event::Idle);
    }
private:
    const WeaponAnimSounds* s_ = nullptr;
    const WeaponAnimSounds::Clip* cur_ = nullptr;
    float t_ = 0.0f;
    bool loop_ = true;
};

// A weapon's projectile (versus WEPDATA WeaponProjectiles[0] -> TnProjectileMesh) [CONF data]: HmProjectile plays
// FlightSound attached to the projectile from spawn (ClientSpawnFlightEffect) and, on Explode, fades it out over 0.25 s
// and plays ExplosionSound at the projectile (SpawnExplosionEffect) [CONF script].
struct WeaponProjectile {
    std::string projectileClass, flightSound, secondaryFlightSound, explosionSound, flightEffect, explosionEffect;
    std::string bounceSound, fuseSound;   // HmProjectile.HitWall / TnProjectileGrenadeBase.HitThing (OnHitThing; fuse start)
};

// A weapon class's WP_Fire presentation templates (WEPMESH MuzzleFlashes / TracerTemplates, DefaultSquib) [CONF data].
struct WeaponFxTemplates { std::string muzzle, tracer, squib; };

// A buff class's sounds (TnBuff ApplySound / UnapplySound, TnBuffCloak team variants, TnBuffDrainSource.HealSound,
// TnBuffDrainTarget.DamageSound, TnBuffHealthOnBlock.ActivationSound), resolved down the class chain [CONF data].
struct BuffSounds {
    std::string apply, unapply, autobotApply, autobotUnapply, decepticonApply, decepticonUnapply, heal, damage, activation;
    bool onlyLocal = true;   // TnBuff.OnlyPlaySoundOnLocalPlayer (default True; TnBuffCloak False)
};

class CharacterAudio {
public:
    static const CharacterAudioProfile* find(const std::string& keyOrName);   // roster chassis key or display name
    static const CharacterAudioProfile& defaultProfile();                    // "Truck" (Optimus Prime)
    static int profileCount();
    static std::vector<std::string> keys();
    // Load the cues the profile references that the cue table does not have yet (level-owned: released with the
    // level's cues). Returns the number added.
    static int loadCues(SoundCues& cues, const CharacterAudioProfile& p);
    // A weapon class's event cue (e.g. "TransContent.TnWeaponIonBlaster", "WP_Fire"); "" if none.
    static const std::string& weaponCue(const std::string& weaponClass, const std::string& event);
    static const std::string& weaponPickupSound(const std::string& weaponClass);
    static int loadWeaponCues(SoundCues& cues, const std::string& weaponClass);
    // The weapon's hit effect (nullptr: no entry matches its damage type -> no hit sound, as in the original).
    static const WeaponHitEffect* weaponHitEffect(const std::string& weaponClass);
    // The weapon mesh's animation sounds (nullptr: no anim set in the data).
    static const WeaponAnimSounds* weaponAnimSounds(const std::string& weaponClass);
    // The weapon's particle templates (nullptr: unknown class).
    static const WeaponFxTemplates* weaponFx(const std::string& weaponClass);
    static const WeaponProjectile* weaponProjectile(const std::string& weaponClass);   // nullptr: instant hit
    static bool weaponIsBeam(const std::string& weaponClass);                         // TnWeaponBeam (Repair Ray)
    // TnAbility.OnTriggerSound by ability class name ("TnAbilityBarrier"; "" if none authored).
    static const std::string& abilityTriggerSound(const std::string& abilityClass);
    static const BuffSounds* buffSounds(const std::string& buffClass);               // "TnBuffCloak"; nullptr: none
    // An authored *Sound field of a Gameplay class Systems voices: TnPlayerController (AbilitiesJammedSound,
    // TransformFailedSound, Killed*Sound, DeathSound), TnAcrobaticsManager (_HoverLoopSound / _HoverCooldownSound),
    // TnRollerMine (_IdleLoopingSound / _BuildupSound / _ExplosionSound). "" if none.
    static const std::string& classSound(const std::string& cls, const std::string& field);
    // TnDamageTypeMelee or a subclass ("TransGame.TnDamageTypeMeleeBerzerk").
    static bool isMeleeDamageType(const std::string& damageType);
    // The SharedHitEffectPlayer entry a damage type selects (exact, else nearest ancestor) with its bCausesBlood gate;
    // nullptr if none. For non-weapon hits (melee, whirlwind, shoulder slam, rams).
    static const WeaponHitEffect* damageHitEffect(const std::string& damageType);
    // Load every ability / buff cue the cue table does not have yet (level-owned, like the weapon cues).
    static int loadAbilityCues(SoundCues& cues);
    // An event's LoopingFadeInTime / LoopingFadeOutTime (WeaponSounds) [CONF data]; 0 / 0 if not authored.
    static void weaponEventFades(const std::string& weaponClass, const std::string& event, float& fadeIn, float& fadeOut);
    // Load the victim's hit / block cues for that weapon (level-owned). Returns the number added.
    static int loadHitCues(SoundCues& cues, const CharacterAudioProfile& victim, const std::string& weaponClass);
};

} // namespace game
