// Clean-room reconstruction — WFC SoundCue playback (HM_Engine SoundNodeRoot + SoundNodeWaveEvent).
//
// WFC cues are not UE3 node graphs but a flat timeline: a SoundNodeRoot (Volume dB, Pitch
// semitones, random variation ranges, DistanceMin/Max + RolloffFactor in UU, SmartPan
// distances, RearAttenuation, an optional SoundParameter, mixer Category, MaxConcurrentPlayCount
// on the cue) whose children are SoundNodeWaveEvents (start Time, Volume/Pitch offsets + variation,
// ChanceToPlayNone, bLooping, a 5.1 pan matrix, a random choice among their SoundNodeWaveEx
// waves, VolumeCurve/PitchCurve over the root's SoundParameter, and an Envelope of volume/pitch
// curves over the cue's playback time). Those are the only node types the slice's cues use
// (weapon, Optimus, vehicle, transformation and all 32 Streets map cues). Values are [CONF]:
// generated by tools/systems/gen_cues.py into SoundCues.inc, or loaded from the map's audio.json.
//   SoundParameters.SOUND_DISTANCE (HmSoundParameterDistanceToListener, Max 18000 UU)
//   SoundParameters.Optimus_Prime_Speed (Max 120): vehicle speed in mph [MED]
//   SoundParameters.Optimus_Prime_Tire_Squeal (Max 1.57 = pi/2): tire slip angle in radians [HI]
#pragma once
#include <functional>
#include <string>
#include <vector>
#include "audio/Audio.h"
#include "core/Math.h"

namespace assets { class Json; }

namespace game {

namespace cuedata {
struct CurvePt { float x, y; };
enum class Param { None, Distance, Speed, TireSqueal };
struct EventDef {
    float time, volDb, volVarMin, volVarMax, pitchSt, pitchVarMin, pitchVarMax;
    int chanceNone;                      // ChanceToPlayNone (percent)
    bool loop;                           // bLooping
    float stereoGain;                    // 5.1 pan matrix folded to stereo (rear-only layers -3 dB)
    std::vector<std::string> waves;      // random pick (content-relative .wav paths)
    std::vector<CurvePt> volCurve;       // over the root SoundParameter (linear gain)
    std::vector<CurvePt> pitchCurve;     // over the root SoundParameter (semitones)
    std::vector<CurvePt> envVol;         // Envelope over playback time (s, linear gain)
    std::vector<CurvePt> envPitch;       // Envelope over playback time (s, semitones)
};
struct CueDef {
    std::string name;
    int maxConcurrent;                   // SoundCue.MaxConcurrentPlayCount (0 = unlimited)
    float volDb, volVarMin, volVarMax, pitchSt, pitchVarMin, pitchVarMax;
    float distMinUU, distMaxUU, rolloff;
    float pan2DUU, pan3DUU;              // SmartPanDistance2D / 3D (class default 400 / 800)
    float rearAttenDb;                   // RearAttenuation (sources behind the listener)
    std::string category;                // SoundMixerCategoryName (SFX_WET_* route through MASTER_WET)
    bool occlusion;                      // EnableOcclusionVolume (class default true)
    Param param;                         // SoundNodeRoot.SoundParameter
    std::vector<EventDef> events;
};
} // namespace cuedata

class SoundCues {
public:
    // Where an instance plays.
    //   kWorld: a fixed world position (impacts, map emitters, positional one-shot pools).
    //   kUI:    non-positional (2D) playback.
    //   any other owner id: attached (an UE3/Hm AudioComponent on an actor, optionally at a named
    //   socket/bone); it follows the owner every tick, including its one-shot and delayed wave
    //   events. Owner ids and sockets are defined by the caller and resolved through setResolver().
    static constexpr int kWorld = -1;
    static constexpr int kUI = -2;
    struct Emitter {
        core::Vec3 pos{0, 0, 0};    // initial / world position
        int owner = kWorld;
        core::Vec3 offset{0, 0, 0}; // owner-space offset, interpreted by the resolver
        std::string socket;         // optional socket / bone on the owner
    };
    using Resolver = std::function<bool(int owner, const std::string& socket, const core::Vec3& offset,
                                        core::Vec3& outPos)>;
    void setResolver(Resolver r) { resolver_ = std::move(r); }
    // Occlusion (UE3 AudioDevice bEnableOcclusion, OcclusionCheckInterval 0.25 s): `blocked(listener,
    // source)` is a world line check; an occluded instance fades to the PhysicalMaterial
    // AudioOcclusionVolume (-6 dB) over AudioOcclusionTransitionTime (0.5 s).
    // `owner` lets the caller test an attached sound against its owner's body rather than a socket tip.
    using OcclusionQuery = std::function<bool(const core::Vec3& from, const core::Vec3& to, int owner)>;
    void setOcclusion(OcclusionQuery q) { occlusion_ = std::move(q); }
    void setListener(const core::Vec3& p) { listener_ = p; }
    int occludedInstances() const;
    // Diagnostics: visit every live instance (resolved position, owner id, occlusion 0..1).
    template <class F> void forEachInstance(F&& f) const {
        for (const Instance& in : live_) f(in.pos, in.owner, in.occl);
    }

    // Load every wave the built-in cue table references (ExtractedAssets/content/<pkg>/<wave>.wav).
    void load(audio::IAudio* a, const std::string& contentRoot);
    // Add the cue graphs of a map's audio.json "cues" object (BL_LVL_* map bank). Returns the count.
    int addCues(const assets::Json& cues, const std::string& contentRoot);
    bool hasCue(const char* name) const { return findCue(name) >= 0; }
    const cuedata::CueDef* cueDef(const char* name) const;

    // Play a cue; returns an instance id (-1 on failure). `distM` drives SOUND_DISTANCE curves (for
    // the local player's own sounds, kSmartPan_PreferPlayer, the distance from the player); `param`
    // feeds the cue's own SoundParameter (vehicle speed in mph, tire slip angle in rad).
    int play(const char* cue, const core::Vec3& pos, float distM, float param = 0.0f);
    int play(const char* cue, const Emitter& em, float distM, float param = 0.0f);
    // Live parameters for a playing (e.g. looping) instance; `pos` is ignored for attached instances.
    void update(int instance, const core::Vec3& pos, float param);
    void setVolume(int instance, float linear);      // AudioComponent VolumeMultiplier / fades
    // Stop an instance, fading its voices out over `fade` seconds (0 = immediate).
    void stop(int instance, float fade);
    bool playing(int instance) const;
    void tick(float dt);

    int activeInstances(const char* cue) const;
    size_t liveInstances() const { return live_.size(); }
    size_t pendingEvents() const { return pending_.size(); }
    // Diagnostics: current resolved position of an instance.
    bool instancePos(int instance, core::Vec3& out) const;

private:
    struct VoiceRef { audio::Voice v; int event; float baseDb, baseSt; };
    struct Pending { int inst; float t; int event; };
    struct Instance {
        int cue; int id; float age; core::Vec3 pos; float distM, param;
        int owner = kWorld; core::Vec3 offset{0, 0, 0}; std::string socket; bool posDirty = false;
        float volume = 1.0f;
        float occl = 0.0f, occlTarget = 0.0f, occlCheck = 0.0f;   // 0 = clear .. 1 = fully occluded
        std::vector<VoiceRef> voices;
        float fade = -1.0f, fadeLeft = 0.0f;   // fade-out duration / remaining (fade < 0 = none)
        bool looping = false;
    };

    int findCue(const char* name) const;
    void loadWaves(size_t cue, const std::string& contentRoot);
    void launch(Instance& in, int event);
    void refresh(Instance& in);
    bool resolve(Instance& in);
    float paramFor(const Instance& in) const;
    Instance* find(int id);

    audio::IAudio* audio_ = nullptr;
    Resolver resolver_;
    OcclusionQuery occlusion_;
    core::Vec3 listener_{0, 0, 0};
    std::vector<cuedata::CueDef> cues_;
    std::vector<std::vector<std::vector<audio::Sound>>> waves_;   // [cue][event][wave]
    std::vector<Instance> live_;
    std::vector<Pending> pending_;
    int nextId_ = 0;
};

} // namespace game
