// Clean-room reconstruction — WFC SoundCue playback (HM_Engine SoundNodeRoot + SoundNodeWaveEvent).
//
// WFC cues are not UE3 node graphs but a flat timeline: a SoundNodeRoot (Volume dB, Pitch
// semitones, random variation ranges, DistanceMin/Max + RolloffFactor in UU, SmartPan
// distances, RearAttenuation, an optional SoundParameter, mixer Category, MaxConcurrentPlayCount
// on the cue) whose children are SoundNodeWaveEvents (start Time, Volume/Pitch offsets + variation,
// ChanceToPlayNone, bLooping, a 5.1 pan matrix, a random choice among their SoundNodeWaveEx
// waves, VolumeCurve/PitchCurve over the root's SoundParameter, and an Envelope of volume/pitch
// curves over the cue's playback time). Those are the only node types the slice's cues use
// (weapon, Optimus, vehicle, transformation, UI, music, and every level-bank cue: Streets' 32, the UI levels').
// Values are [CONF]: generated by tools/systems/gen_cues.py into SoundCues.inc, or loaded from a level manifest.
//   SoundParameters.SOUND_DISTANCE (HmSoundParameterDistanceToListener, Max 18000 UU)
//   SoundParameters.Optimus_Prime_Speed (Max 120): vehicle speed in mph [MED]
//   SoundParameters.Optimus_Prime_Tire_Squeal (Max 1.57 = pi/2): tire slip angle in radians [HI]
#pragma once
#include <chrono>
#include <functional>
#include <future>
#include <map>
#include <string>
#include <vector>
#include "audio/Audio.h"
#include "core/Math.h"
#include "game/SoundMixer.h"

namespace assets { class Json; }

namespace game {

namespace cuedata {
struct CurvePt { float x, y; };
enum class Param { None, Distance, Speed, TireSqueal };
// SoundNodeRoot.SpatializationType [CONF HM_Engine enum]: 0 k3D (class default), 1 k2D, 2 kSmartPan,
// 3 kSmartPan_PreferPlayer.
enum class Spatial { ThreeD, TwoD, SmartPan, SmartPanPreferPlayer };
// SoundCue.InstanceLimiting [CONF Engine enum; class default kKillFarthest].
enum class Limit { KillOldest, KillNewest, KillFarthest };
struct EventDef {
    float time, volDb, volVarMin, volVarMax, pitchSt, pitchVarMin, pitchVarMax;
    int chanceNone;                      // ChanceToPlayNone (percent)
    bool loop;                           // bLooping
    float stereoGain;                    // 5.1 pan matrix folded to stereo (rear-only layers -3 dB)
    std::vector<std::string> waves;      // random pick (content-relative .wav paths)
    std::vector<CurvePt> volCurve;       // over the root SoundParameter (linear gain)
    std::vector<CurvePt> pitchCurve;     // over the root SoundParameter (semitones)
    std::vector<CurvePt> envVol;         // Envelope over playback time (s, linear gain)
    std::vector<CurvePt> envPitch;       // Envelope over playback time (s, semitones)
    bool overridePriority;               // OverridePriority: use `priority` instead of the root's
    float priority;                      // SoundNodeWaveEvent.Priority
};
struct CueDef {
    std::string name;
    int maxConcurrent;                   // SoundCue.MaxConcurrentPlayCount (0 = unlimited; class default 5)
    Limit limit;                         // SoundCue.InstanceLimiting
    float volDb, volVarMin, volVarMax, pitchSt, pitchVarMin, pitchVarMax;
    float distMinUU, distMaxUU, rolloff;
    float pan2DUU, pan3DUU;              // SmartPanDistance2D / 3D (class default 400 / 800)
    float panAtten3DDb;                  // SmartPanAttenuation3D (gain toward fully 3D)
    float rearAttenDb;                   // RearAttenuation (sources behind the listener)
    std::string category;                // SoundMixerCategoryName (SFX_WET_* route through MASTER_WET)
    std::string mixerPreset;             // PlayMixerPreset (SoundMixerPresetName), "" = none
    bool occlusion;                      // EnableOcclusionVolume (class default true)
    Spatial spatial;                     // k2D plays non-positional [CONF]
    Param param;                         // SoundNodeRoot.SoundParameter
    std::vector<EventDef> events;
    float priority;                      // SoundNodeRoot.Priority (unset = 0)
    bool mapBank;                        // added by a map's audio.json (removed at map unload)
    // SoundNodeRoot bLooping + LoopStart / LoopEnd: the root playback time wraps at LoopEnd back to LoopStart and
    // the wave events re-run on the cue's timeline [RE A6 0x827881D8 pseudocode; HIGH for the re-run].
    bool rootLoop;
    float loopStart, loopEnd;
    // Streamed: waves decoded when the cue first plays and released when no instance is left (music).
    bool streamed;
};
} // namespace cuedata

class SoundCues {
public:
    // Where an instance plays.
    //   kWorld: a fixed world position (impacts, map emitters, positional one-shot pools).
    //   kUI:    non-positional (2D) playback.
    //   any other owner id: attached (an UE3/Hm AudioComponent on an actor, optionally at a named
    //   socket/bone); it follows the owner every tick, including its one-shot and delayed wave
    //   events. Owner ids and sockets are defined by the caller and resolved through setResolver().
    static constexpr int kWorld = -1;
    static constexpr int kUI = -2;
    static constexpr int kParticipantOwnerBase = 1000;      // owner ids >= this are other participants' pawns (World)
    struct Emitter {
        core::Vec3 pos{0, 0, 0};    // initial / world position
        int owner = kWorld;
        core::Vec3 offset{0, 0, 0}; // owner-space offset, interpreted by the resolver
        std::string socket;         // optional socket / bone on the owner
    };
    using Resolver = std::function<bool(int owner, const std::string& socket, const core::Vec3& offset,
                                        core::Vec3& outPos)>;
    void setResolver(Resolver r) { resolver_ = std::move(r); }
    // Occlusion (UE3 AudioDevice bEnableOcclusion, OcclusionCheckInterval 0.25 s): `blocked(listener,
    // source)` is a world line check; an occluded instance fades to the PhysicalMaterial
    // AudioOcclusionVolume (-6 dB) over AudioOcclusionTransitionTime (0.5 s).
    // `owner` lets the caller test an attached sound against its owner's body rather than a socket tip.
    using OcclusionQuery = std::function<bool(const core::Vec3& from, const core::Vec3& to, int owner)>;
    void setOcclusion(OcclusionQuery q) { occlusion_ = std::move(q); }
    void setListener(const core::Vec3& p) { listener_ = p; }
    int occludedInstances() const;
    // Diagnostics: visit every live instance (resolved position, owner id, occlusion 0..1).
    template <class F> void forEachInstance(F&& f) const {
        for (const Instance& in : live_) f(in.pos, in.owner, in.occl);
    }
    // Diagnostics: one line per live attached (or all, `worldToo`) instance: cue, owner/socket,
    // source, listener, distance, pan, attenuation, occlusion, first voice's channel gains.
    void logSpatial(const char* tag, const core::Vec3& ownerPos, bool worldToo) const;

    // Load every wave the built-in cue table references (ExtractedAssets/content/<pkg>/<wave>.wav).
    void load(audio::IAudio* a, const std::string& contentRoot);
    // Add the cue graphs of a map's audio.json "cues" object (the map's sound bank). Returns the count.
    // MaxConcurrentPlayCount / InstanceLimiting: the entry's own fields (the level manifest's cue_limits are merged in
    // by AmbientAudio::load), else Engine.Default__SoundCue (5 / kKillFarthest).
    int addCues(const assets::Json& cues, const std::string& contentRoot);
    // A localized wave's file for the selected language's _LOC twin ("" = no such twin extracted: not played).
    static std::string localizedWave(const std::string& rel, const std::string& ownerTwin, const std::string& contentRoot,
                                     bool account = true);   // account = false: no LocStats / warnings (prefetch warming)
    // Localized waves resolved so far: from the selected _LOC twin / the merged copy (it is that twin) / not played.
    struct LocStats { int twin = 0, merged = 0, skipped = 0; };
    static LocStats& locStats();

    // ---- lifecycle ----
    // Hard stop of every instance (voices stopped at once, queued wave events dropped, cue mixer presets
    // released). Used for map unload and frontend transitions.
    void stopAll();
    // Stop every instance of a non-map cue (player weapon / vehicle / foley / transform / UI): match reset.
    int stopNonMapInstances();
    // Map unload: stop the map bank's instances, remove its cues and release their samples. Returns cues removed.
    int unloadMapCues();
    int mapCueCount() const;
    // Release the decoded waves of streamed cues with no live instance (also done every tick).
    int releaseIdleStreams();
    // Decode a streamed cue's waves ahead of its first play (e.g. on a loading screen); they stay resident until
    // the cue has played and its last instance ended. Returns false for an unknown cue.
    // Prefetch a streamed cue for an upcoming level (loading screen). On a backend with thread-safe loading the waves
    // are decoded on a worker (the device's sample cache is warmed) and adopted by the next tick (cache hits) - the
    // frame that asks no longer blocks on the decode (37-94 ms frontend hitch). Otherwise decoded now.
    bool prefetch(const char* cue);
    ~SoundCues() {                                     // inline: every build links it
        for (Warm& w : warming_) if (w.done.valid()) w.done.wait();
        for (LevelWarm& w : levelWarm_) if (w.done.valid()) w.done.wait();
        for (Orphan& w : orphans_) if (w.done.valid()) w.done.wait();
        unregisterTable(this);
    }
    int warmingPrefetches() const { return (int)warming_.size(); }
    int orphanDecodes() const { return (int)orphans_.size(); }
    int waitingInstances() const { int n = 0; for (const Instance& in : live_) n += in.waiting ? 1 : 0; return n; }
    // Level-start warming (frontend frame budget): decode the eager (non-streamed, non-localized) waves of a manifest cue
    // bank for an upcoming level `tag` on a worker, so the level's addCues finds them in the device cache. Thread-safe
    // backends only (else 0). Returns the number of waves queued.
    int warmCueWaves(const assets::Json& cues, const std::string& contentRoot, const std::string& tag);
    void waitWarm(const std::string& tag);             // before loading `tag`: its warm decodes are finished
    // After loading `keep`: forget its warm records (adopted) and release every other tag's warmed samples no cue owns
    // (a prefetched level that never loaded). Returns the samples released.
    int releaseWarmExcept(const std::string& keep);
    int warmLevels() const { return (int)levelWarm_.size(); }
    // Drop a prefetch pin (the prefetching level was abandoned): the normal idle-stream release frees it.
    void unpin(const char* cue);
    // Diagnostics: a streamed cue's waves are resident (decoded) right now.
    bool wavesResident(const char* cue) const;
    size_t cueCount() const { return cues_.size(); }
    bool hasCue(const char* name) const { return findCue(name) >= 0; }
    // The FmodAudioDevice mixer (presets, categories, MASTER_WET environment).
    SoundMixer& mixer() { return mixer_; }
    const SoundMixer& mixer() const { return mixer_; }
    // FSB4 sample-header loop regions (AssetTools 7a69756 vehicle_audio_loops.json -> VehicleLoops.inc,
    // applied by load()) [CONF data]: every looping vehicle wave's region is its whole sample [0, total-1]; no
    // slice FSB sample (1929) has a custom range, so other looping waves use the same whole-sample default.
    // [CONF native, RE d50c2a9 P1] Looping is enabled only by the wave node: SoundNodeWaveEvent.bLooping ->
    // FMOD_LOOP_NORMAL at channel create (0x82768820); WFC sets no loop points or loop count, so FMOD loops the
    // FSB region 0..N-1 indefinitely. Neither the cue root LoopStart / LoopEnd nor the FSB header loop flag is
    // consulted. Returns the entries applied.
    int applyLoopPoints();
    const cuedata::CueDef* cueDef(const char* name) const;
    void setMaxConcurrent(const char* name, int n) { int c = findCue(name); if (c >= 0) cues_[(size_t)c].maxConcurrent = n; }

    // Play a cue; returns an instance id (-1 on failure). `distM` drives SOUND_DISTANCE curves (for
    // the local player's own sounds, kSmartPan_PreferPlayer, the distance from the player); `param`
    // feeds the cue's own SoundParameter (vehicle speed in mph, tire slip angle in rad).
    int play(const char* cue, const core::Vec3& pos, float distM, float param = 0.0f);
    int play(const char* cue, const Emitter& em, float distM, float param = 0.0f);
    // A dialogue cue on an HmDialogComponent whose DialogCharacter is `dialogCharacter` (e.g. DialogCharacters.OPRIME):
    // only the wave events of that character (and those with none) play.
    int playDialog(const char* cue, const Emitter& em, const std::string& dialogCharacter);
    // Live parameters for a playing (e.g. looping) instance; `pos` is ignored for attached instances.
    void update(int instance, const core::Vec3& pos, float param);
    void setVolume(int instance, float linear);      // AudioComponent VolumeMultiplier / fades
    void fadeIn(int instance, float seconds);        // AudioComponent.FadeIn(FadeInDuration, 1.0)
    // Stop an instance, fading its voices out over `fade` seconds (0 = immediate).
    void stop(int instance, float fade);
    bool playing(int instance) const;
    void tick(float dt);

    int activeInstances(const char* cue) const;
    // The cue definition an instance plays (null if gone); the oldest live instance of a cue (-1 if none).
    const cuedata::CueDef* instanceCue(int instance) const;
    int oldestInstance(const char* cue) const;
    size_t liveInstances() const { return live_.size(); }
    int inaudibleSkipped() const { return inaudibleSkipped_; }   // one-shots not started: beyond their audible distance
    size_t pendingEvents() const { return pending_.size(); }
    // Diagnostics: "cue x count" for queued wave events, most first.
    std::string pendingSummary() const;
    // Diagnostics: current resolved position of an instance.
    bool instancePos(int instance, core::Vec3& out) const;

private:
    struct VoiceRef { audio::Voice v; int event; float baseGain, baseSt; };
    struct Pending { int inst; float t; int event; };
    struct Instance {
        int cue; int id; float age; core::Vec3 pos; float distM, param;
        int owner = kWorld; core::Vec3 offset{0, 0, 0}; std::string socket; bool posDirty = false;
        float volume = 1.0f;
        float occl = 0.0f, occlTarget = 0.0f, occlCheck = 0.0f;   // 0 = clear .. 1 = fully occluded
        float fadeInLen = 0.0f;                                   // FadeIn ramp over the instance age
        float lastGain = 1.0f;                                    // gainOf() at the last refresh
        bool waiting = false;     // a streamed cue still decoding on the worker: starts (age 0) when its waves are adopted
        std::vector<VoiceRef> voices;
        float fade = -1.0f, fadeLeft = 0.0f;   // fade-out duration / remaining (fade < 0 = none)
        bool looping = false;
        std::string dialogChar;                                   // playDialog: the component's DialogCharacter
    };

    int findCue(const char* name) const;
    void loadWaves(size_t cue, const std::string& contentRoot);
    void launch(Instance& in, int event);
    void refresh(Instance& in);
    bool resolve(Instance& in);
    static float level(const Instance& in);
    float paramFor(const Instance& in) const;
    void retire(size_t liveIndex);              // remove an instance (stop voices, disable its mixer preset)
    // Instance level x the mixer's category volume (linear amplitude) for the cue's category.
    float gainOf(const Instance& in) const {
        const std::string& cat = cues_[(size_t)in.cue].category;
        return level(in) * mixer_.categoryVolume(cat) * SoundMixer::groupScale(cat) * mixer_.masterScale();
    }
    SoundMixer mixer_;
    std::string contentRoot_;
    std::map<size_t, std::vector<std::string>> dialogChars_;    // cue -> per-event DialogCharacter (level cues)
    std::string nextDialogChar_;
    Instance* find(int id);

    audio::IAudio* audio_ = nullptr;
    Resolver resolver_;
    OcclusionQuery occlusion_;
    core::Vec3 listener_{0, 0, 0};
    std::vector<cuedata::CueDef> cues_;
    std::vector<std::vector<std::vector<audio::Sound>>> waves_;   // [cue][event][wave]
    std::vector<char> resident_;                                   // [cue] waves decoded (streamed cues: on demand)
    std::vector<char> pinned_;                                     // [cue] prefetched, not yet played
    void releaseWaves(size_t cue);
    std::vector<Instance> live_;
    std::vector<Pending> pending_;
    int nextId_ = 0;
    int inaudibleSkipped_ = 0;
    // Prefetch warming (worker decodes; adopted on the main thread). Every load / release / unload path drains first.
    struct Warm { size_t cue; std::vector<std::string> paths; std::string name; long long bytes = 0;
                  std::chrono::steady_clock::time_point start; std::future<void> done; };
    // Worker decodes nobody waits for any more (their level unloaded / their prefetch was abandoned): their samples are
    // released when they finish, unless a cue owns them or a live decode needs the same file. Never waited on in play.
    struct Orphan { std::vector<std::string> paths; std::string what; std::future<void> done; };
    std::vector<Orphan> orphans_;
    int processOrphans();                             // every live table's orphans (any table's tick: the frontend's
                                                      // orphaned music is released during a match too)
    int processOwnOrphans();
    bool ownsSample(audio::Sound h) const;
    // The live cue tables (main thread only): the frontend's and the match World's share the device's path cache, so an
    // orphan is released only if NO table owns or needs that file.
    static std::vector<SoundCues*>& tables() { static std::vector<SoundCues*> t; return t; }   // inline: every build links it
    static void unregisterTable(SoundCues* t) {
        auto& v = tables();
        for (size_t i = 0; i < v.size(); ++i) if (v[i] == t) { v.erase(v.begin() + (long)i); break; }
    }
    void orphanWarm(Warm& w);
    bool pathNeeded(const std::string& path) const;
    // A main-thread wait on a worker decode (logged when > 5 ms: freeze diagnosis).
    static void timedWait(std::future<void>& f, const char* why, const std::string& what);
    std::vector<Warm> warming_;
    struct LevelWarm { std::string tag; std::vector<std::string> paths; std::future<void> done; };
    std::vector<LevelWarm> levelWarm_;
    void adoptWarm(bool wait, long onlyCue = -1);
    bool startWarm(size_t cue);                       // queue the cue's waves on a worker (false: not thread-safe / no waves)
    bool isWarming(size_t cue) const;
    // Total bytes of a cue's wave files (cached): a large streamed cue (music, tens-hundreds of MB) is decoded on the worker
    // at play; a small one (HUD ticks, dialogue lines, ~0.1 MB) is decoded at once so it starts on time.
    long long waveBytes(size_t cue);
    std::vector<long long> waveBytes_;
    void startInstance(Instance& in);                 // launch the t=0 events, queue the timed ones
};

} // namespace game
