// Generates src/game/CameraTable.inc: per-chassis vehicle camera strategy values from the chassis' HmCameraStrategySet
// (roster_package re_identity.cameras) in AssetTools authored.db (read-only). Strategy roles: Hovering
// (HoveringCameraStrategyType; tanks and jets use their DrivingCameraStrategyType while hovering), Driving (boost),
// Flying (TnFlyingCameraStrategyType, jets). Values: anchor Offset Z (UU), orbit distance (UU), pitch range (deg), FOV.
const {DatabaseSync} = require('node:sqlite');
const fs = require('fs');
const AT = 'F:/Transformers Rebuild/AssetTools/manifests/';
const db = new DatabaseSync(AT + 'authored.db', {readOnly: true});
const get = op => { const r = db.prepare('select props from objects where opath=?').get(op); return r ? JSON.parse(r.props) : null; };
const R = JSON.parse(fs.readFileSync(AT + 'mp_content/roster_package.json', 'utf8'));
const list = Array.isArray(R.chassis) ? R.chassis : Object.values(R.chassis);
function strategy(op) {
  if (!op) return null;
  const pkg = op.split('.')[0], name = op.split('.').slice(1).join('.');
  const rows = db.prepare("select class, opath, props from objects where opath like ?").all(op + '.%');
  const v = {anchor: 0, dist: 0, pmin: -20, pmax: 30, fov: 80};
  for (const r of rows) {
    const p = JSON.parse(r.props);
    if (r.class.includes('AnchorPoint') && p.Offset) v.anchor = p.Offset.Z || 0;
    if ((r.class.includes('LocationOffset')) && p.DefaultOrbitDistance) v.dist = p.DefaultOrbitDistance;
    if (r.class.includes('LocationOffset') && p.LocationOffset && !v.dist) v.dist = -(p.LocationOffset.X || 0);
    if (r.class.includes('OrbitRotationCameraBehavior') && p.DefaultLookSpeed && p.DefaultLookSpeed.PitchRange) { v.pmin = p.DefaultLookSpeed.PitchRange.Min; v.pmax = p.DefaultLookSpeed.PitchRange.Max; }
    if (r.class.includes('FlyingFollowCameraBehavior') && p.PitchRange) { v.pmin = p.PitchRange.Min; v.pmax = p.PitchRange.Max; if (p.AnchorOffset) v.anchor = p.AnchorOffset.Z || v.anchor; }
    if (r.class.includes('Fov') && p.DefaultFOV) v.fov = p.DefaultFOV.Fov;
  }
  return v;
}
const f = x => Number(x).toFixed(3) + 'f';
const rows = [];
for (const c of list) {
  const id = c.re_identity.UniqueId, cs = c.re_identity.cameras;
  const set = cs ? get(cs) : null;
  if (!set) continue;
  const by = t => (set.Strategies || []).find(s => s.Type === t);
  const drive = by('TransGame.TnDrivingCameraStrategyType'), hover = by('TransGame.TnHoveringCameraStrategyType'), fly = by('TransGame.TnFlyingCameraStrategyType');
  const H = strategy((hover || drive || {}).Strategy), D = strategy((drive || {}).Strategy), F = strategy((fly || {}).Strategy);
  if (!H) continue;
  const z = {anchor: 0, dist: 0, pmin: 0, pmax: 0, fov: 0};
  const row = v => `${f(v.anchor * 0.01)}, ${f(v.dist * 0.01)}, ${f(v.pmin)}, ${f(v.pmax)}, ${f(v.fov)}`;
  rows.push(`    {"${id}", ${row(H)}, ${row(D || H)}, ${row(F || z)}},   // ${cs}`);
}
fs.writeFileSync('src/game/CameraTable.inc', `// GENERATED by tools/gameplay/gen_camera_table.js - do not edit. Per chassis: hover {anchor m, orbit m, pitch min / max deg,
// FOV}, driving {...}, flying {...} from the chassis' HmCameraStrategySet strategies (AssetTools authored.db).
${rows.join('\n')}
`);
console.log('rows', rows.length);
