// Read-only: vehicle PhysicsAsset convex-hull bounds (ConvexElems only: element 0 of VH_Optimus_PHYSSYS reproduces the
// Pass 17 hull exactly) per chassis from AssetTools authored.db (BodySetup.AggGeom
// ConvexElems / BoxElems / SphereElems / SphylElems, bone space UE units). Output data/gameplay/vehicle_hulls.json.
const {DatabaseSync} = require('node:sqlite');
const fs = require('fs');
const db = new DatabaseSync('F:/Transformers Rebuild/AssetTools/manifests/authored.db', {readOnly: true});
const get = op => { const r = db.prepare('select props from objects where opath=?').get(op); return r ? JSON.parse(r.props) : null; };
const ids = ['Car','Car2','Car3','Car4','Car5','Car6','Car7','Jet','Jet2','Jet3','Jet4','Jet5','Jet6','Jet7','Jet8','Tank','Tank2','Tank3','Tank4','Tank5','Truck','Truck2','Truck3','Truck4','Truck5','Truck6','Truck7'];
const out = {source: 'AssetTools authored.db (read-only) vehicle PhysicsAsset BodySetup AggGeom bounds, bone space UU; generated by Gameplay tools/gameplay/vehicle_hulls.js', chassis: {}};
for (const id of ids) {
  const c = JSON.parse(fs.readFileSync(`F:/Transformers Rebuild/ExtractedAssets/VerticalSlice/Characters/${id}/character.json`, 'utf8'));
  const pa = c.vehicle.physics_asset;
  const pv = pa ? get(pa) : null;
  if (!pv) { out.chassis[id] = {physics_asset: pa, error: 'not in authored.db'}; continue; }
  const lo = [1e9, 1e9, 1e9], hi = [-1e9, -1e9, -1e9];
  const bones = [];
  const add = (x, y, z) => { const p = [x, y, z]; for (let k = 0; k < 3; ++k) { lo[k] = Math.min(lo[k], p[k]); hi[k] = Math.max(hi[k], p[k]); } };
  for (const b of pv.BodySetup || []) {
    const bv = get(b); if (!bv) continue;
    if (bv.bNoCollision) continue;
    const ag = bv.AggGeom || {};
    let n = 0;
    for (const ce of ag.ConvexElems || []) for (const v of ce.VertexData || []) { add(v.X || 0, v.Y || 0, v.Z || 0); ++n; }
    if (false) for (const bx of ag.BoxElems || []) { const t = (bx.TM && bx.TM.WPlane) || {X: 0, Y: 0, Z: 0}; const hx = (bx.X || 0) / 2, hy = (bx.Y || 0) / 2, hz = (bx.Z || 0) / 2;
      add(t.X - hx, t.Y - hy, t.Z - hz); add(t.X + hx, t.Y + hy, t.Z + hz); ++n; }
    if (false) for (const s of ag.SphereElems || []) { const t = (s.TM && s.TM.WPlane) || {X: 0, Y: 0, Z: 0}; const r = s.Radius || 0; add(t.X - r, t.Y - r, t.Z - r); add(t.X + r, t.Y + r, t.Z + r); ++n; }
    bones.push({bone: bv.BoneName, elements: n});
  }
  out.chassis[id] = {physics_asset: pa, bodies: bones, bounds_ue: {lo, hi}};
  console.log(id.padEnd(7), pa.padEnd(48), JSON.stringify(bones.map(b => b.bone + ':' + b.elements)), 'x', lo[0].toFixed(0), hi[0].toFixed(0), 'y', lo[1].toFixed(0), hi[1].toFixed(0), 'z', lo[2].toFixed(0), hi[2].toFixed(0));
}
fs.writeFileSync('F:/Transformers Rebuild/Rebuild-Gameplay/data/gameplay/vehicle_hulls.json', JSON.stringify(out, null, 1));
