// Read-only: weapon class CDO -> MultiplayerData / PlayerData (TnWeaponData) with class defaults, from AssetTools
// authored.db. Output: data/gameplay/weapons_mp.json (generated; provenance inside).
const {DatabaseSync} = require('node:sqlite');
const fs = require('fs');
const db = new DatabaseSync('F:/Transformers Rebuild/AssetTools/manifests/authored.db', {readOnly: true});
const get = op => { const r = db.prepare('select class, props from objects where opath=?').get(op); return r ? {cls: r.class, p: JSON.parse(r.props)} : null; };
const W = JSON.parse(fs.readFileSync('F:/Transformers Rebuild/AssetTools/manifests/mp_content/mp_weapons.json', 'utf8')).weapons;
// class default chain for TnWeaponData
const defaults = {};
for (const d of ['HM_Engine.Default__HmWeaponData', 'TransGame.Default__TnWeaponData']) { const o = get(d); if (o) Object.assign(defaults, o.p); }
const out = {source: 'AssetTools authored.db (read-only): <weapon class CDO>.MultiplayerData / PlayerData objects over Default__TnWeaponData; ' +
                     'generated by Gameplay work/pass22/weapons_mp.js', defaults_from: Object.keys(defaults).length, weapons: {}};
for (const w of Object.values(W)) {
  const cdoPath = w.class.replace('TransContent.', 'TransContent.Default__');
  const cdo = get(cdoPath);
  if (!cdo) { console.log('no CDO', w.class); continue; }
  const rec = {class: w.class, providers: w.provider_ids, type: w.weapon_type_code, display: w.display_name && w.display_name.INT,
               cdo: {bInstantHit: cdo.p.bInstantHit, ItemName: cdo.p.ItemName}};
  for (const k of ['MultiplayerData', 'PlayerData']) {
    const op = cdo.p[k];
    const o = op ? get(op) : null;
    rec[k] = op ? {object: op, values: o ? Object.assign({}, defaults, o.p) : null} : null;
  }
  out.weapons[w.class] = rec;
}
fs.writeFileSync('F:/Transformers Rebuild/Rebuild-Gameplay/data/gameplay/weapons_mp.json', JSON.stringify(out, null, 1));
const ib = out.weapons['TransContent.TnWeaponIonBlaster'];
console.log('IonBlaster MP', JSON.stringify(ib.MultiplayerData.values.InstantHitDamage), ib.MultiplayerData.values.InitialReserveAmmoCount, JSON.stringify(ib.MultiplayerData.values.RangeDamageModifiers));
const ar = out.weapons['TransContent.TnWeaponAssaultRifle'];
console.log('AR MP', ar.MultiplayerData && JSON.stringify(ar.MultiplayerData.values).slice(0, 600));
let n = 0, mp = 0; for (const r of Object.values(out.weapons)) { n++; if (r.MultiplayerData && r.MultiplayerData.values) mp++; } console.log('weapons', n, 'with MP data', mp);
