"""Generate src/game/PickupPresentation.inc from AssetTools manifests/streets_pickup_factories.json (7a69756,
read-only): the 27 placed MP_IAC_Streets pickup factories with the presentation data Systems owns (pickup
sound, effect components and their spawn activation, highlight flag). Positions are converted UE -> glTF
metres (x, z, y) / 100, as every other Streets table.
Run with AssetTools/bin/py/python.exe:  python tools/systems/gen_pickups.py <out.inc>
"""
import io, json, sys

MAN = 'F:/Transformers Rebuild/AssetTools/manifests/streets_pickup_factories.json'
KIND = {'TnAmmoCratePickupFactory': 'Kind::AmmoCrate', 'TnHealthPickupFactory': 'Kind::Health',
        'TnOverShieldPickupFactory': 'Kind::OverShield', 'TnGameObjectivePickupFactoryFlag': 'Kind::ObjectiveFlag',
        'TnGameObjectivePickupFactoryBomb': 'Kind::ObjectiveBomb'}

m = json.load(io.open(MAN, encoding='utf-8'))
cls = m['factory_classes']

def prop(c, name, default):
    v = cls[c]['factory_properties'].get(name)
    return default if v is None or v.get('value') is None else v['value']

def q(s):
    return '"%s"' % s if s else 'nullptr'

out = ['// Generated by tools/systems/gen_pickups.py from AssetTools manifests/streets_pickup_factories.json (7a69756) - do not edit.\n',
       '// {actor, kind, UE location, glTF position (m), RespawnTime, PickupSound cue, CustomPickupEffect template,\n',
       '//  PickupEffect template, PickupEffect attached (in Components), ShouldDisplayHighlightFx, RequiredGameRuleClass}\n',
       'const FactoryDef kFactories[] = {\n']
for inst in m['instances']:
    c = inst['class']
    loc = inst['transform']['Location']
    inv = cls[c]['inventory']['payload']
    sound = (inv.get('PickupSound') or {}).get('value')
    eff = inst['effects']
    custom = eff.get('CustomPickupEffect', {}).get('Template')
    pickup = eff.get('PickupEffect', {}).get('Template')
    attached = cls[c]['effect_components']['PickupEffect']['in_Components_array']['value']
    respawn = (inst.get('RespawnTime') or {}).get('value')
    if respawn is None: respawn = prop(c, 'RespawnTime', 0.0)
    rule = prop(c, 'RequiredGameRuleClass', None)
    out.append('    {"%s", %s, {%.4ff, %.4ff, %.4ff}, {%.5ff, %.5ff, %.5ff}, %.1ff, %s, %s, %s, %s, %s, %s},\n' % (
        inst['actor'].split('.')[-1], KIND[c], loc['X'], loc['Y'], loc['Z'],
        loc['X'] * 0.01, loc['Z'] * 0.01, loc['Y'] * 0.01, float(respawn), q(sound), q(custom), q(pickup),
        'true' if attached else 'false', 'true' if prop(c, 'ShouldDisplayHighlightFx', False) else 'false', q(rule)))
out.append('};\n')
io.open(sys.argv[1], 'w', encoding='utf-8').write(''.join(out))
print('factories', len(m['instances']), m['counts']['instances_by_class'])
