"""Generate src/game/SoundMixer.inc from the cooked SoundConfig.SoundMixerProperties (via AssetTools
authored.db, read-only): the mixer presets the slice uses and the per-category DSP values of the two
categories Systems applies (SFX_WET_VEH_ENGINE volume, MASTER_WET reverb / echo / volume).
Run with AssetTools/bin/py/python.exe:  python tools/systems/gen_mixer.py <out.inc>
"""
import io, json, sqlite3, sys

DB = 'F:/Transformers Rebuild/AssetTools/manifests/authored.db'
PRESETS = ['VEHICLE_JUMP', 'VEHICLE_BOOST_END'] + ['REVERB_TRANS_MP_STREETS_' + z for z in (
    'EXTERIOR', 'NEU_BASE', 'AUTO_ROOM_01', 'DEC_ROOM_LOWER', 'NEU_HALL', 'TRAIN_DEPOT', 'AUTO_ROOM_02',
    'TRAIN_TUNNEL', 'NEU_STAIRWELL', 'DEC_ROOM_UPPER')]
CATS = ['SFX_WET_VEH_ENGINE', 'MASTER_WET']

c = sqlite3.connect(DB)
d = json.loads(c.execute("select props from objects where opath='SoundConfig.SoundMixerProperties'").fetchone()[0])
mp = {p['Name']: p for p in d['MixerPresets']}
cats = {k['Name']: k for k in d['SoundCategories']}

def f(x):
    s = '%.7g' % x
    return s + ('f' if ('.' in s or 'e' in s) else '.0f')

out = ['// Generated by tools/systems/gen_mixer.py from SoundConfig.SoundMixerProperties - do not edit by hand.\n']
# Presets (the built-in "Default" is added by the mixer itself: Priority 0, fades 0.5, Duration -1).
out.append('const PresetDef kPresetDefs[] = {\n')
for n in PRESETS:
    p = mp[n]
    out.append('    {"%s", %s, %s, %s, %s},\n' % (n, f(p['Priority']), f(p['FadeInTime']), f(p['FadeOutTime']), f(p['Duration'])))
out.append('};\n')
# Per category: every DSP preset the category defines (name -> values), incl. "Default".
for cn in CATS:
    cat = cats[cn]
    out.append('// %s (DSPEffectConfig %d)\n' % (cn, cat.get('DSPEffectConfig', 0)))
    out.append('const CategoryPreset k%s[] = {\n' % ''.join(w.capitalize() for w in cn.split('_')))
    for p in cat['DSPPresets']:
        if p['Name'] != 'Default' and p['Name'] not in PRESETS:
            continue
        r, e = p['Reverb'], p['Echo']
        vals = [p['Volume']['Volume'], r['Room'], r['RoomHF'], r['RoomRolloffFactor'], r['DecayTime'], r['DecayHFRatio'],
                r['ReflectionsLevel'], r['ReflectionsDelay'], r['Level'], r['Delay'], r['Diffusion'], r['Density'],
                r['HFReference'], e['Delay'], e['DecayRatio'], e['WetMix'], e['DryMix']]
        out.append('    {"%s", {%s}},\n' % (p['Name'], ', '.join(f(v) for v in vals)))
    out.append('};\n')
io.open(sys.argv[1], 'w', encoding='utf-8').write(''.join(out))
print('presets', len(PRESETS))
