"""Generate src/game/SoundMixer.inc from the cooked SoundConfig.SoundMixerProperties (via AssetTools
authored.db, read-only): the global mixer presets Systems enables and, for EVERY sound category, the DSP values of
its Default preset and of those presets (Volume + MASTER_WET reverb / echo; the other DSP stages are not applied).
Run with AssetTools/bin/py/python.exe:  python tools/systems/gen_mixer.py <out.inc>
"""
import io, json, re, sqlite3, sys

DB = 'F:/Transformers Rebuild/AssetTools/manifests/authored.db'
# Global presets: the ones the built-in cues play (PlayMixerPreset) and Engine.MovieSettings MovieMixerPreset
# (Xe-TransEngine.ini MovieMixerPreset=CINE_MUTE_FOR_BINK, enabled while a Bink movie plays). Map reverb presets are
# NOT compiled in: a level's manifest reverb_presets register them at load (SoundMixer::addMapPreset).
PRESETS = ['VEHICLE_JUMP', 'VEHICLE_BOOST_END', 'CINE_MUTE_FOR_BINK']

INI = 'F:/Transformers Rebuild/ExtractedAssets/config/Coalesced_ini/TransGame/Config/Xenon/Cooked/Xe-TransEngine.ini'
ini = io.open(INI, encoding='utf-8', errors='replace').read()
UNFLUSHABLE = re.findall(r'^UnflushableMixerPresets=(\S+)', ini, re.M)       # [HM_Engine.SoundMixerProperties]
ALWAYS = re.findall(r'^MoviesToAlwaysPlaySound=(\S+)', ini, re.M)           # [Engine.MovieSettings]
MOVIE = re.findall(r'^MovieMixerPreset=(\S+)', ini, re.M)                   # [HM_Engine.FmodAudioDevice]
assert MOVIE and MOVIE[0] in PRESETS, MOVIE

c = sqlite3.connect(DB)
d = json.loads(c.execute("select props from objects where opath='SoundConfig.SoundMixerProperties'").fetchone()[0])
mp = {p['Name']: p for p in d['MixerPresets']}

def f(x):
    s = '%.7g' % x
    return s + ('f' if ('.' in s or 'e' in s) else '.0f')

out = ['// Generated by tools/systems/gen_mixer.py from SoundConfig.SoundMixerProperties - do not edit by hand.\n']
# Presets (the built-in "Default" is added by the mixer itself: Priority 0, fades 0.5, Duration -1).
out.append('const PresetDef kPresetDefs[] = {\n')
for n in PRESETS:
    p = mp[n]
    out.append('    {"%s", %s, %s, %s, %s},\n' % (n, f(p['Priority']), f(p['FadeInTime']), f(p['FadeOutTime']), f(p['Duration'])))
out.append('};\n')
# Per category (authored order): the DSP presets it defines among Default + PRESETS.
out.append('// {category, preset, Volume, Reverb (12), Echo (4)}\n')
out.append('const CategoryRow kCategoryRows[] = {\n')
nondef = []
for cat in d['SoundCategories']:
    for p in cat['DSPPresets']:
        if p['Name'] != 'Default' and p['Name'] not in PRESETS:
            continue
        r, e = p['Reverb'], p['Echo']
        vals = [p['Volume']['Volume'], r['Room'], r['RoomHF'], r['RoomRolloffFactor'], r['DecayTime'], r['DecayHFRatio'],
                r['ReflectionsLevel'], r['ReflectionsDelay'], r['Level'], r['Delay'], r['Diffusion'], r['Density'],
                r['HFReference'], e['Delay'], e['DecayRatio'], e['WetMix'], e['DryMix']]
        out.append('    {"%s", "%s", {%s}},\n' % (cat['Name'], p['Name'], ', '.join(f(v) for v in vals)))
        if p['Name'] == 'Default' and abs(vals[0] - 1.0) > 1e-6: nondef.append((cat['Name'], round(vals[0], 4)))
out.append('};\n')
# Xe-TransEngine.ini: presets a mixer Flush (level change) keeps, and the movie preset.
out.append('const char* const kUnflushablePresets[] = {%s};\n' % ', '.join('"%s"' % n for n in UNFLUSHABLE))
out.append('const char* const kMovieMixerPresetName = "%s";\n' % MOVIE[0])
out.append('const char* const kMoviesToAlwaysPlaySound[] = {%s};\n' % ', '.join('"%s"' % n for n in sorted(set(ALWAYS))))
# Master's Default DSP compressor (global; DSPEffectConfig bit 32 = compressor stage [MED]).
m = [k for k in d['SoundCategories'] if k['Name'] == 'Master'][0]
mc = [p for p in m['DSPPresets'] if p['Name'] == 'Default'][0]['Compressor']
out.append('// Master Default compressor {DSPEffectConfig, Threshold dB, Attack ms, Release ms, GainMakeup dB}\n')
out.append('const float kMasterCompressor[5] = {%s, %s, %s, %s, %s};\n' % (
    f(m['DSPEffectConfig']), f(mc['Threshold']), f(mc['Attack']), f(mc['Release']), f(mc['GainMakeup'])))
# Category tree (authored ChildCategories): FMOD category volumes multiply down the tree, so a sound group's volume
# reaches every descendant of its categories.
out.append('// {category, parent} from SoundCategories ChildCategories (Master is the root)\n')
out.append('const CategoryParent kCategoryParents[] = {\n')
nparents = 0
for cat in d['SoundCategories']:
    for ch in cat.get('ChildCategories') or []:
        out.append('    {"%s", "%s"},\n' % (ch if isinstance(ch, str) else ch['Name'], cat['Name'])); nparents += 1
out.append('};\n')
# [HM_Engine.SoundMixerProperties] SoundGroupCategoryMappings: SetAudioGroupVolume(group) -> these categories.
GROUPS = re.findall(r'^SoundGroupCategoryMappings=\(GroupName=(\w+),\s*CategoryNames=\(([^)]*)\)\)', ini, re.M)
assert GROUPS, 'SoundGroupCategoryMappings'
# SetAudioGroupVolume REPLACES each listed category's fader (initialised to the category's config Volume) with the
# slider value [CONF RE pass 5 §10]. The rebuild applies it as a multiplier on the subtree, which is identical only
# while those config Volumes are 1.0 - check it.
cfgVol = {k['Name']: k['Volume'] for k in d['SoundCategories']}
for g, cats in GROUPS:
    for cn in [x.strip() for x in cats.split(',') if x.strip()]:
        assert abs(cfgVol[cn] - 1.0) < 1e-6, ('group category config Volume != 1', g, cn, cfgVol[cn])
out.append('// {group, category} from Xe-TransEngine.ini SoundGroupCategoryMappings\n')
out.append('const GroupCategory kGroupCategories[] = {\n')
for g, cats in GROUPS:
    for cn in [x.strip() for x in cats.split(',') if x.strip()]:
        out.append('    {"%s", "%s"},\n' % (g, cn))
out.append('};\n')
# Profile defaults (TnProfileSettings DefaultSettings): Music Volume 31, FX Volume 32, Dialogue Volume 33 (0..100);
# HmPlayerController.UpdateLocalCacheOfProfileSettings applies them as SetAudioGroupVolume(group, value / 100).
ps = json.loads(c.execute("select props from objects where opath='TransGame.Default__TnProfileSettings'").fetchone()[0])
dv = {x['ProfileSetting']['PropertyId']: x['ProfileSetting']['Data']['Value1'] for x in ps['DefaultSettings']}
out.append('// TnProfileSettings defaults: {group, slider 0..100}\n')
out.append('const GroupDefault kProfileGroupDefaults[] = {{"MUSIC", %d}, {"SFX", %d}, {"DIALOG", %d}};\n' % (dv[31], dv[32], dv[33]))
io.open(sys.argv[1], 'w', encoding='utf-8', newline='\n').write(''.join(out))
print('presets', len(PRESETS), 'categories', len(d['SoundCategories']), 'parents', nparents, 'groups', GROUPS,
      'profile defaults', dv[31], dv[32], dv[33], 'Default volume != 1:', nondef)
