"""Generate src/game/SoundMixer.inc from the cooked SoundConfig.SoundMixerProperties (via AssetTools
authored.db, read-only): the global mixer presets Systems enables and, for EVERY sound category, the DSP values of
its Default preset and of those presets (Volume + MASTER_WET reverb / echo; the other DSP stages are not applied).
Run with AssetTools/bin/py/python.exe:  python tools/systems/gen_mixer.py <out.inc>
"""
import io, json, re, sqlite3, sys

DB = 'F:/Transformers Rebuild/AssetTools/manifests/authored.db'
# Global presets: the ones the built-in cues play (PlayMixerPreset) and Engine.MovieSettings MovieMixerPreset
# (Xe-TransEngine.ini MovieMixerPreset=CINE_MUTE_FOR_BINK, enabled while a Bink movie plays). Map reverb presets are
# NOT compiled in: a level's manifest reverb_presets register them at load (SoundMixer::addMapPreset).
PRESETS = ['VEHICLE_JUMP', 'VEHICLE_BOOST_END', 'CINE_MUTE_FOR_BINK']

INI = 'F:/Transformers Rebuild/ExtractedAssets/config/Coalesced_ini/TransGame/Config/Xenon/Cooked/Xe-TransEngine.ini'
ini = io.open(INI, encoding='utf-8', errors='replace').read()
UNFLUSHABLE = re.findall(r'^UnflushableMixerPresets=(\S+)', ini, re.M)       # [HM_Engine.SoundMixerProperties]
MOVIE = re.findall(r'^MovieMixerPreset=(\S+)', ini, re.M)                   # [HM_Engine.FmodAudioDevice]
assert MOVIE and MOVIE[0] in PRESETS, MOVIE

c = sqlite3.connect(DB)
d = json.loads(c.execute("select props from objects where opath='SoundConfig.SoundMixerProperties'").fetchone()[0])
mp = {p['Name']: p for p in d['MixerPresets']}

def f(x):
    s = '%.7g' % x
    return s + ('f' if ('.' in s or 'e' in s) else '.0f')

out = ['// Generated by tools/systems/gen_mixer.py from SoundConfig.SoundMixerProperties - do not edit by hand.\n']
# Presets (the built-in "Default" is added by the mixer itself: Priority 0, fades 0.5, Duration -1).
out.append('const PresetDef kPresetDefs[] = {\n')
for n in PRESETS:
    p = mp[n]
    out.append('    {"%s", %s, %s, %s, %s},\n' % (n, f(p['Priority']), f(p['FadeInTime']), f(p['FadeOutTime']), f(p['Duration'])))
out.append('};\n')
# Per category (authored order): the DSP presets it defines among Default + PRESETS.
out.append('// {category, preset, Volume, Reverb (12), Echo (4)}\n')
out.append('const CategoryRow kCategoryRows[] = {\n')
nondef = []
for cat in d['SoundCategories']:
    for p in cat['DSPPresets']:
        if p['Name'] != 'Default' and p['Name'] not in PRESETS:
            continue
        r, e = p['Reverb'], p['Echo']
        vals = [p['Volume']['Volume'], r['Room'], r['RoomHF'], r['RoomRolloffFactor'], r['DecayTime'], r['DecayHFRatio'],
                r['ReflectionsLevel'], r['ReflectionsDelay'], r['Level'], r['Delay'], r['Diffusion'], r['Density'],
                r['HFReference'], e['Delay'], e['DecayRatio'], e['WetMix'], e['DryMix']]
        out.append('    {"%s", "%s", {%s}},\n' % (cat['Name'], p['Name'], ', '.join(f(v) for v in vals)))
        if p['Name'] == 'Default' and abs(vals[0] - 1.0) > 1e-6: nondef.append((cat['Name'], round(vals[0], 4)))
out.append('};\n')
# Xe-TransEngine.ini: presets a mixer Flush (level change) keeps, and the movie preset.
out.append('const char* const kUnflushablePresets[] = {%s};\n' % ', '.join('"%s"' % n for n in UNFLUSHABLE))
out.append('const char* const kMovieMixerPresetName = "%s";\n' % MOVIE[0])
# Master's Default DSP compressor (global; DSPEffectConfig bit 32 = compressor stage [MED]).
m = [k for k in d['SoundCategories'] if k['Name'] == 'Master'][0]
mc = [p for p in m['DSPPresets'] if p['Name'] == 'Default'][0]['Compressor']
out.append('// Master Default compressor {DSPEffectConfig, Threshold dB, Attack ms, Release ms, GainMakeup dB}\n')
out.append('const float kMasterCompressor[5] = {%s, %s, %s, %s, %s};\n' % (
    f(m['DSPEffectConfig']), f(mc['Threshold']), f(mc['Attack']), f(mc['Release']), f(mc['GainMakeup'])))
io.open(sys.argv[1], 'w', encoding='utf-8', newline='\n').write(''.join(out))
print('presets', len(PRESETS), 'categories', len(d['SoundCategories']), 'Default volume != 1:', nondef)
