"""Generate src/game/PickupPresentation.inc from AssetTools manifests/streets_pickup_factories.json (read-only):
per pickup FACTORY CLASS, its InventoryType and the inventory CDO's PickupSound (Inventory.AnnouncePickup plays it
on the receiving pawn). Class data, not placement: any map's factories of these classes use the same sounds.
Run with AssetTools/bin/py/python.exe:  python tools/systems/gen_pickups.py <out.inc>
"""
import io, json, sys

MAN = 'F:/Transformers Rebuild/AssetTools/manifests/streets_pickup_factories.json'
m = json.load(io.open(MAN, encoding='utf-8'))
out = ['// Generated by tools/systems/gen_pickups.py from AssetTools manifests/streets_pickup_factories.json - do not edit.\n',
       '// {factory class, InventoryType, inventory CDO PickupSound (null = none authored)}\n',
       'const PickupClassSound kPickupClassSounds[] = {\n']
for cls, d in sorted(m['factory_classes'].items()):
    if 'factory_properties' not in d or 'inventory' not in d:
        continue                                            # the shared TnPickupFactory base
    inv = d['factory_properties']['InventoryType']['value']
    snd = (d['inventory']['payload'].get('PickupSound') or {}).get('value')
    out.append('    {"%s", "%s", %s},\n' % (cls, inv, '"%s"' % snd if snd else 'nullptr'))
out.append('};\n')
io.open(sys.argv[1], 'w', encoding='utf-8').write(''.join(out))
print(''.join(out))
