"""Generate src/game/CookedCueLimits.inc from AssetTools manifests/vertical_slice_audio_concurrency.json (read-only):
every cue whose cooked SoundCue AUTHORS MaxConcurrentPlayCount and/or InstanceLimiting (origin "authored").
SoundCues::addCues falls back to this table when a map's audio.json "cues" entry does not carry the field, then
to Engine.Default__SoundCue (5 / kKillFarthest). Map-agnostic: it is a cue-asset table, not a per-map branch.
Run with AssetTools/bin/py/python.exe:  python tools/systems/gen_cue_limits.py <out.inc>
"""
import io, json, sys

MAN = 'F:/Transformers Rebuild/AssetTools/manifests/vertical_slice_audio_concurrency.json'
LIMIT = {'kKillOldest': 'Limit::KillOldest', 'kKillNewest': 'Limit::KillNewest', 'kKillFarthest': 'Limit::KillFarthest'}

m = json.load(io.open(MAN, encoding='utf-8'))
rows = []
for c in m['cues']:
    mc, il = c['cue_fields']['MaxConcurrentPlayCount'], c['cue_fields']['InstanceLimiting']
    if mc['origin'] != 'authored' and il['origin'] != 'authored':
        continue
    rows.append('    {"%s", %d, %s},\n' % (c['cue'], int(mc['value']), LIMIT[il['value']]))
out = ['// Generated by tools/systems/gen_cue_limits.py from AssetTools vertical_slice_audio_concurrency.json - do not edit.\n',
       '// {cue, MaxConcurrentPlayCount, InstanceLimiting} for cues that author either field (cooked SoundCue).\n',
       'const CookedCueLimit kCookedCueLimits[] = {\n'] + sorted(rows) + ['};\n']
io.open(sys.argv[1], 'w', encoding='utf-8').write(''.join(out))
print('authored cue limits', len(rows))
