"""Generate src/game/VehicleLoops.inc from AssetTools manifests/vehicle_audio_loops.json (AssetTools 7a69756,
read-only): the FSB4 sample-header loop region of every wave that a looping (bLooping) wave event of the
Optimus vehicle audio component plays. Checks each against the extracted .wav (rate, channels, frames).
Run with AssetTools/bin/py/python.exe:  python tools/systems/gen_loops.py <out.inc>
"""
import io, json, struct, sys

MAN = 'F:/Transformers Rebuild/AssetTools/manifests/vehicle_audio_loops.json'
CONTENT = 'F:/Transformers Rebuild/ExtractedAssets/content/'

def wav_info(path):
    d = open(path, 'rb').read()
    off, rate, ch, frames = 12, 0, 0, 0
    while off + 8 <= len(d):
        cid, sz = d[off:off + 4], struct.unpack('<I', d[off + 4:off + 8])[0]
        if cid == b'fmt ':
            ch, rate = struct.unpack('<HI', d[off + 10:off + 16])
        elif cid == b'data':
            frames = sz // (2 * ch)
        off += 8 + sz + (sz & 1)
    return rate, ch, frames

m = json.load(io.open(MAN, encoding='utf-8'))
looping = set()
for slot in m['slots']:
    for we in slot.get('wave_events', []):
        if we.get('bLooping', {}).get('value'):
            looping.update(we['waves'])
out = ['// Generated by tools/systems/gen_loops.py from AssetTools manifests/vehicle_audio_loops.json (7a69756) - do not edit.\n',
       '// FSB4 header census: %d samples, %d with a custom loop range, %d with a LOOP mode flag.\n'
       % (m['census']['fsb4_samples'], m['census']['with_custom_loop_range'], m['census']['with_LOOP_mode_flag']),
       '// {wav, sample rate, channels, total samples, loop start, loop end (inclusive), header loop flag}\n',
       'const FsbLoop kFsbLoops[] = {\n']
for name in sorted(looping):
    w = m['waves'][name]
    pkg, nm = name.split('.', 1)
    wav = '%s/%s.wav' % (pkg, nm)
    rate, ch, frames = wav_info(CONTENT + wav)
    assert (rate, ch, frames) == (w['sample_rate'], w['channels'], w['total_samples']), (name, rate, ch, frames)
    lp = w['loop']
    out.append('    {"%s", %d, %d, %d, %d, %d, %s},\n' % (wav, w['sample_rate'], w['channels'], w['total_samples'],
               lp['loopstart_sample'], lp['loopend_sample'], 'true' if lp['loop_enabled_in_sample_header'] else 'false'))
out.append('};\n')
io.open(sys.argv[1], 'w', encoding='utf-8').write(''.join(out))
print('looping waves', len(looping))
