"""Embeds third_party/ffx_fsr1/ffx_a.h + ffx_fsr1.h (MIT, unmodified) as C++ raw strings for the GLSL upscaler
shaders: writes src/render/gl/FfxFsr1Source.inc. Rerun after updating the vendored headers."""
import os
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
out = ['// Generated by tools/render/embed_ffx.py from third_party/ffx_fsr1 (AMD FidelityFX FSR 1, MIT licence: see',
       '// third_party/ffx_fsr1/LICENSE.txt). Do not edit.']
for name, var in (('ffx_a.h', 'kFfxA'), ('ffx_fsr1.h', 'kFfxFsr1')):
    src = open(os.path.join(root, 'third_party', 'ffx_fsr1', name), encoding='utf-8').read()
    assert ')FFX"' not in src
    chunks = [src[i:i + 30000] for i in range(0, len(src), 30000)]   # (string literal size limits on some compilers)
    out.append('static const char* const %s[] = {' % var)
    out += ['R"FFX(%s)FFX",' % c for c in chunks]
    out.append('};')
open(os.path.join(root, 'src', 'render', 'gl', 'FfxFsr1Source.inc'), 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print('ok')
